# .github/workflows/devsecops.yml 
name: DevGuard DevSecOps

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    call-devsecops:
        uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
        with:
            asset-name: "campus-velbert-heiligenhaus/projects/campus-velbert-heiligenhaus/assets/cvh-camera"
            api-url: "https://api.devguard.org"
            web-ui: "https://app.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings 
